# -*- coding: utf-8 -*-
#
# Need Groups
#
NeedGroup.delete_all
ng1 = NeedGroup.create(:name => 'Most predictive needs')
ng2 = NeedGroup.create(:name => 'Trust and commitment')
ng3 = NeedGroup.create(:name => 'Companionship')
ng4 = NeedGroup.create(:name => 'Comunication styles')
ng5 = NeedGroup.create(:name => 'Family')

#
# Needs
#
Need.delete_all
n1 = Need.create(:name=>"Admiration", :description=>"Admiring and holding your partner in esteem is an important need. We feel pride and value as a mate when we let our partner know we really like them and value them and show them this by concrete actions. To hold your partner as a top priority in your life helps you feel like a real lover. Of course on the other side, being admired and liked by your partner is also an important need. It feeds a deep place in our soul to know that we are noticed, seen and valued by our partner, especially when he or she shows us that in ways that are important to us. Letting each other know the ways in which we feel admired and liked is an important component of getting this need met", :need_group_id=> ng1.id, :oneliner=>"knowing your partner really likes and admires you")

n2 = Need.create(:name=>"Acceptance", :description=>"We want to be loved for who we are and what we are. There is nothing more amazing than to feel that it is your self that your partner is attracted to or in love with, not things that you do or a role that you play. Acceptance is conveyed when your partner listens, appreciates and values you just as you are, without trying to change you. 
When your partner listens, appreciates, and converses with you, without trying to change you, you feel accepted. Conversely, when you are criticized, and judged, you do not feel accepted. To accept your partner the way they are, does not mean you have to believe they are perfect, but only that you love them just the way they are and have no intention to improve them. When a partner feels fully accepted, it is much easier for them to listen and provide full understanding and empathy to you.", :need_group_id=> ng2.id, :oneliner=>"The need to feel your partner is  content with you without needing to change you")
  
n3 = Need.create(:name=>"Appreciation", :description=>"In any moderately successful relationship both people are pulling some of the weight. Sometime the work is complementary as in when one works outside the home and the other works inside the home. At other times the responsibilities are shared with both doing some of each task. The point is we want to be seen and acknowledged for what we do contribute. We want to be appreciated for the efforts we are making to keep the relation-ship afloat. We want our dedication, hard work, commitment, and sacrifices to register on the radar of our partner and even more, to feel that they notice and value what we are contributing. The thank you’s and acknowledgements close the circuit in a partnership, fueling and reinforcing the continuation of the contribution. At the same time it is important to be the appreciator: to notice and see what our beloved is doing to contribute to the community of family life. To be an appreciator is to come out of our own little world and be mindful and aware of the joint enterprise. This too is an important need as it expands and ennobles us to reach out and really see and express gratitude for the efforts being made.", :need_group_id=> ng2.id, :oneliner=>"The need to be appreciated")

n4 = Need.create(:name=>"Autonomy", :description=>"By autonomy, we mean the need to be free to make one's own choices, to feel a sense of freedom in the relationship, and to be free of domination by or coercion from our partner. And keep in mind, that domination is sometimes done by invoking guilt, and other more subtle means, not just by outright demands or threats. 
In the end, however, autonomy is something taken, not given. Even in oppressive situations or relationships (except perhaps where there are physical threats and violence) we can develop a sense of our own worth or uniqueness and find our own way. It is important that we find our own inner freedom and value instead of expecting our partner to grant it to us.
When there are differences between two partners, or if there are needs not being met, it is important to make requests, not demands. Among second marriages, the need for autonomy is often very strong among women, who have come out of domineering former marriages. See 'Resolving Differences' for more on the difference between a request and a demand.", :need_group_id=> ng4.id, :oneliner=>"The need to feel you  are not being controlled")

n5 = Need.create(:name=>"To be Known", :description=>"Deep down inside we want to be known for who we really are. This raises the stakes in the development of intimacy in a relationship. To be known means we have to risk showing ourselves to our partner and to let him or her see and hear what we think, feel and desire. The risk, of course, is that we can be rebuffed or rejected for our truths or at least make our partner feel awkward or uncomfortable. The alternative however is not to be known and to therefore to be loved and desired only for the false self we show. Its risky to be honest, genuine and truthful, but to find acceptance and care from someone who really truly knows us is deeply satisfying. To have this need met is really in our own hands, at least to start with.", :need_group_id=> ng1.id, :oneliner=>"The need to for your partner to know  the most important things about you")    

n6 = Need.create(:name=>"Respect", :description=>"Respect is the need to be acknowledged as a separate autonomous person in the relationship. Even though our partner may not agree or feel comfortable with what we are doing, saying or feeling we want them to respect our right to have our own experience that may be different from theirs. We do not want to be coerced, bullied or shamed into changing. On the other hand we also have a need to be respectful. We have a need to be autonomous by acknowledging autonomy. We need to stand on our own two feet while our partner stands on theirs. This mutual respect is the maturest forms of relating. It signifies we are not scared to let others be themselves.", :need_group_id=> ng1.id, :oneliner=>"The need to be respected")

n7 = Need.create(:name=>"Connection and Concern", :description=>"Connection is the need to feel attached to and in touch with our partner. We are connected when we can go about our day and carry an image of our partner and know what they are doing and what is important to them. We have the desire to check in with them, electronically or by literally by skin throughout the day and week. Couples who feel this need is met have rituals of connection and disconnection, beginning the day by a conscious hello, going off to work with a conscious goodbye and coming together in the evening and really being present to one another for a few moments of reconnection. It is wonderful to feel our partner is thinking about us, looks for us, reaches out to us. This need is about both the need to initiate the connection (to be the lover) and to be reached (to be the beloved). 
If you have not checked the needs for communication and respect we recommend you choose this need.", :need_group_id=> ng1.id, :oneliner=>"The need for your partner to be present with & concerned about you")

n8 = Need.create(:name=>"Communication", :description=>"The need for communication has two aspects: the first is the ability to speak your thoughts and emotions to your partner in a way that he/she understands and the second is be able to hear your partners thoughts and emotions in a way that they feel understood. Communication is therefore about both sending and receiving a message so that it goes from person A to person B and is not garbled along the way. To be clear and effective in communication is extremely satisfying and gives you confidence that you can get your other needs met. At the same time to be receptive and open to what your partner has to say and express is also satisfying. No one likes to feel closed and defensive. We generally like feeling open. 
Conversation with your partner is very important. If you fail to meet this need it may also influence your ability to fulfill other needs. It helps couples communicate their needs to each other and learn how to meet each other's needs. When partners take part in conversation that really communicates this information about their needs, they learn to become more compatible.
To start such a conversation, ask what your partner thinks and feels. One evening you might use questions such as these: \"What has made you feel good today? What has made you feel bad?\" Then let your partner know what made you feel good today and what made you feel bad", :need_group_id=> ng1.id, :oneliner=>"The need for your partner to express her honest feelings, thoughts, needs")    

n9 = Need.create(:name=>"Common Higher Purpose", :description=>"Relationships are strengthened by a shared sense of purpose. To feel a sense of common purpose, both partners must embrace similar causes, strive to achieve or understand something greater than themselves. For some, this may come in the form of devotion to a religion; for others, perhaps, a dedication to volunteering at a homeless shelter, or lobbying efforts on behalf of an environmental cause or peace effort. A common purpose can unite a couple in ways that go beyond simply sharing similar views on a topic, for the devotion to that purpose generally prompts action which is shared by the couple. Such ventures can provide very powerful bonding experiences.
 
Common purpose may also be thought of as shared dreams. Many couples share in common dreams for themselves and their family, and by that we do not just mean the dream of owning a big house or nice car. Some examples of these shared dreams may include a shared sense of freedom, adventure, justice and honor; a oneness with nature; self-exploration and embarking on a spiritual journey together. In some situations, these dreams may not be shared by both you and your partner.What is important in these cases is that these dreams are not hidden or suppressed, and that the one in the relationship who may not have that dream, at the very least respects that the other one does.", :need_group_id=> ng1.id, :oneliner=>"The need to share a common higher purpose in life")    

n10 = Need.create(:name=>"Domestic/Financial Support", :description=>"These are two types of grease that keep the wheels of a relationship turning. They are two sides of the same coin: if we are the sole bread winner, we need the support at home. If we manage the household full time, we need a partner who responsibly brings home the bacon. We feel much more generous in getting up to go to work, on the one hand, or in running the household,on the other, if we have the sense that our partner is putting in a comaparable effort. The trouble is that it is hard to guage what is comparable. Usuallly we feel that what we do is more difficult and that our partner has it easy. He gets to go off and build a career and be rewarded directly for it. She gets all that discretionary time around the house and bonds more with the kids. This is a major area for hurt feelings and conflict and it is especially difficult when both partners do some ofboth: earn a salary and do work at home. We have a deep sense of fairness that often gets tweaked in this area and fights about who does what and who does more are very common. A little understanding of what the other person does in their realm and what motivates them to do it, can often restore a sense of fairness.", :need_group_id=> ng5.id, :oneliner=>"The need for your partner to do his/her share to support the home/family phisically and financially")    

n11 = Need.create(:name=>"Family Commitment", :description=>"The majority of women and men have a powerful instinct to create a family. We get great satisfaction in committing ourselves to the mental, emotional and spiritual development of our children, or where there are no children, to extended family and community causes. When we are rising to the challenge of this commitment and we feel our partner right along side of us, we are generous and open with our time and resources because we know that we are helping to foster and create something beyond ourselves. The deep need to contribute to the flourishing of those who are part of us or who are in our community is compelling.
With regard to nuclear families we know that parents have a profound influence on their children. Parenting takes time, lots of time, and quality time—for the express purpose of teaching children the value of cooperation and care for each other. According to Harley, fifteen hours per week is what is needed. And this time needs to be planned, that schedules time together for meals, going for walks or bike rides, attending religious services, conducting family meetings, playing games, reading before bedtime, helping the children with school or financial planning, and family projects. Being a devoted parent takes training as well, consistency, and knowing how to handle anger, and how to resolve conflicts with each other over parenting.", :need_group_id=> ng5.id, :oneliner=>"The need for your partner to be committed to emotional welfare of the family")    

n12 = Need.create(:name=>"Devotion", :description=>"At times we need to feel that our partner is devoted to us. That means he or she holds us in high esteem, often looks up to us, takes pride in us, sometimes even treats us with adoration, in whatever form that has meaning in our relationship. This quality has to be nurtured and developed as the years go on and we become familiar with each other. To feel that our partner sees the best in us and cherishes us for ourself creates very deep intimacy (into-me-you-see). If our partner sees into us and deeply knows us and because of that knowing values us, this is the deepest kind of love. It heals all. There are many ways to foster devotion, as you soon will see.", :need_group_id=> ng2.id, :oneliner=>"The need to know your partner is loyal and adores you")

n13 = Need.create(:name=>"Honesty and Openness", :description=>"This is the need to be who we really are with our partner and to trust that our partner is being who they really are with us. It is doing what you say and saying what you mean. The sense of integrity that this represents is fulfilling, even though there might be consequences. But the willingness to face the consequences of our truthfulness is a sign of growth and maturity and of a solid sense of self. The need for honesty, can jump start a relationship into a new phase of growth, as long held back resentments and grievances can begin to be aired and worked through. Responsible honesty, however, means telling the truth with good timing, minimizing blame and judgment (if the truth is about our partner’s effect on us) or with gentleness and compassion (if the truth is about ourselves). Having an agreement that anything can be talked about (but doesn’t necessarily have to be) is a healthy step to move a relationship forward. ", :need_group_id=> ng1.id, :oneliner=>"The need for complete honesty from your partner")    

n14 = Need.create(:name=>"Affection", :description=>"Affection is the glue that holds a relationship together. It is expressed through touch, warmth, softness, play, and responsive laughter. Affection signifies that we are noticed, cared about and valued and that our partner is willing and wanting to reach out and touch us (literally or figuratively). Often we have the misconception that our partner should know what we want in terms of affection. It’s important to be clear about the type of affection we want to receive by telling our partner specifically what form it should take (i.e. hugs, kisses, a touch on the arm, speaking endearments, or even helping wash the dishes. Our partners must learn to give the type of affection we need, not what they need or think we need.
For Most Women Affection must Come Before Sex It is also very important that a man understand the place affection holds in their sexual relationship—that for a woman, sex must begin with affection. Giving affection helps build intimacy for women, which in turn often leads to them having more sexual desire. Unfortunately, many affairs begin because of what the husband perceives as a lack of sex, but what the wife perceives as a lack of affection. He may feel the relationship is lacking physically, so he feels less inclined to show affection; meanwhile, she feels a lack of affection so she may in turn be less interested in having sex. This vicious cycle will continue until it is understood that good sexual relations must begin with a real sense of affection, especially from the man toward the woman.", :need_group_id=> ng3.id, :oneliner=>"The need for touch, warmth, play & laughter from your partner")

n15 = Need.create(:name=>"Personal Growth/Stimulation", :description=>" ", :need_group_id=> ng4.id, :oneliner=>"The need for intellectual and/or spiritual stimulation from your partner")

n16 = Need.create(:name=>"Recreational Companionship", :description=>"We need to have fun and in a committed relationship we want to have fun with our partner, at least some of the time. To engage in activities that elicit our curiosity, passion, adrenaline, and/or excitement is deeply human and it can be so much more satisfying to do it, at least occasionally, with someone you love. At the same time it can be expanding to let go and give ourselves over to the activities that turn our partner on, recreationally. We can learn new things and stretch ourselves a bit. Obviously there has to be a balance with each partner playing the following roles: as the inviter, occasionally encouraging and including the other in the fun and excitement, and as the invitee, occasionally expanding limits and trying something new and different at the bequest of the other. 
 
Recreation is good for the soul, especially if we see it in terms of re-creation or building up and invigorating ourselves. Sport, adventure, nature, exercise are all good for the body and spirit and it is important to know what our partner likes to do in this area and to let our partner know what we like to do and then occasionally participate in each other’s passion or interest", :need_group_id=> ng3.id, :oneliner=>"The need for fun TOGETHER")    

n17 = Need.create(:name=>"To Contribute", :description=>"Contrary to those among us who believe that humans are innately selfish, aggressive, warlike, and violent, there is also abundant research to prove that all humans, except those severely wounded in their childhood, have a need to contribute to those around them. In a healthy loving relationship, each partner shares in contributing to the needs of a relationship in many ways. Some of the more obvious include monetary contribution, domestic support, and sexual interaction. On a deeper level, however, relationships invite each participant to contribute to the personal growth and welfare of their partner--= beyond the financial, sexual, and domestic. For example, some writers think men need to contribute to the woman’s sense of security, and the woman needs to contribute to the man’s sense of self-worth. Each can usefully recognize the needs of the other, and then act upon those needs by contributing whatever is necessary for the others fulfillment. This mutual contribution will help to build appreciation, respect, and a sense of reciprocity.", :need_group_id=> ng5.id, :oneliner=>"The need to feel you are really helping your partner in major ways") 

n18 = Need.create(:name=>"To Trust", :description=>"Trust is the need to have faith and confidence in your partner and to feel your partner has faith and confidence in you. If your partner says he is going to do something, you know he will do it. If she promises you something, you know she will follow through. At the same time we feel the need to be trustworthy. We all want to act with integrity and to live up to our pledges. (Wonder why we don’t trust politicians?) We want to be our better self in our relationship. Another part of trust is sensing that our partner has our best interests in mind, a good portion of the time. We can rely on him or her to take our wants and desires into account when decisions have to be made. This allows for a sense of safety and security in the relationship which fosters growth. ", :need_group_id=> ng2.id, :oneliner=>"To Trust The need to be able to trust your partner's integrity (not necessarily all competencies)")

n19 = Need.create(:name=>"To be Trusted", :description=>"Trust is the need to have faith and confidence in your partner and to feel your partner has faith and confidence in you. If your partner says he is going to do something, you know he will do it. If she promises you something, you know she will follow through. At the same time we feel the need to be trustworthy. We all want to act with integrity and to live up to our pledges. (Wonder why we don’t trust politicians?) We want to be our better self in our relationship. Another part of trust is sensing that our partner has our best interests in mind, a good portion of the time. We can rely on him or her to take our wants and desires into account when decisions have to be made. This allows for a sense of safety and security in the relationship which fosters growth.", :need_group_id=> ng2.id, :oneliner=>"The need to know your partner trusts your own integrity")

n20 = Need.create(:name=>"Understanding", :description=>"We desperately want to be understood and there is nothing that can compare with feeling that our partner “gets us”, meaning that he or she knows what we do, why we do it, and how we feel about it.  Mutual understanding cuts through a lot of difficulties and sometimes just sitting down and updating our partner on whats up for us and letting him or her do the same to us, soothes a lot of hurts and clears up a lot of mistaken assumptions.  The need to be understood carries with it the responsibility of knowing yourself and risking letting your partner in.  But if he or she welcomes your truth while at the same time honoring their own truth, then the deepest kind of mutual understanding has occurred.", :need_group_id=> ng4.id, :oneliner=>"The need to feel your partner really understands you deeply and completely")  

n21 = Need.create(:name=>"Reciprocity", :description=>"Reciprocity refers to the give and take of a relationship. If partners feel they are being given to as much as they are giving, this is reciprocity. Betty Ford once said that “a marriage won’t work if each feels it’s a 0-50 proposition. Each needs to feel it’s a 70-30 proposition.” We assume she meant that sometimes she gave more and at other times Gerald gave more but in the long run it came out fairly even. A wife needs to feel as though the husband is contributing to the relationship and family as much as she is, and vice versa. Reciprocity does not imply a one-to-one correspondence of contributions or a tit for tat relationship(e.g., the wife does the dishes, so the husband feels he must due his equal duty by taking out the garbage) – Rather, each gives to the other out of a developed generosity, and both the husband and wife must feel like overall, they are each doing their part to make the relationship work. Although reciprocity frequently means an exchange of similar behavior and/or treatment, it is often more similar to dancing, wherein both partners cannot put the same foot forward at the same time. In other words, good reciprocity requires a give and take between partners, and it is only valuable when it involves feelings of love, mutual respect and cooperation, without a sense of compulsion.", :need_group_id=> ng3.id, :oneliner=>"The need to feel your partner is as concerned with your needs as you are with his")    

n22 = Need.create(:name=>"Safety", :description=>" ", :need_group_id=> ng5.id, :oneliner=>"The need to feel physically and emotinally safe at all times with your partner")    

n23 = Need.create(:name=>"Openness to My Influence", :description=>"Letting ourselves be influenced is a tough one but we think it is one of those needs that is given a bad name and so is not recognized as crucial for a relationship. We believe that far from being wimpish or caving in, being open to influence takes great strength and we all need to feel our strength in a relationship. Openness to influence means the need to be challenged and changed by our partner. To take the hit when we mess up. To own our own \"stuff\". This takes courage -to not be defensive or attack back. This is a satisfying quality to see in ourselves- that we can be open. It is one of the higher human needs.", :need_group_id=> ng2.id, :oneliner=>"The need to know your partner seriously considers your suggestions")

n24 = Need.create(:name=>"Peace & Harmony", :description=>"Sometimes we long for calm and ease and the sense that things are just right between us and our partner. This occurs when there are no conflicts or resentments simmering under the surface and moreover, there is compatibility, cooperation, and the sense that things are just as they should be. This need for what we call peace and harmony is a deep one: it signifies a break in the storm or the end of a season of difficulty or the warm light of hard work paying off. When these periods of calm are not simply brief interludes but rather a growing foundation of the relationship, it is deeply satisfying. We feel good about ourselves and our partner and the enterprise we have embarked on together. Feeling this, we think that the net result of all our effort and challenge was worth it.", :need_group_id=> ng4.id, :oneliner=>"The need for peace and harmony in your couple and family life")

n25 = Need.create(:name=>"Sexual Fulfillment", :description=>"We all have the need to be sexual, not just physically, but also emotionally and even spiritually. We want to feel desire, savor growing arousal, linger in that turned on place where we are really into each other and, in most cases, but not all or at least not every time, achieve an orgasm that rocks our boat. We all have a lot to learn about each of these phases: how to elicit and fan the flames of desire, how to please and turn on our partner and how to invite our partner to turn us on; how to slow things down a bit when they build up speed, in order to build up intensity; and how to have our orgasms involve all of us, not just our genitals.
Sex is one of the most difficult things to talk about in a relationship and yet we often fumble around trying to read our partners signals and hoping they read ours. This is, however, an area where once the taboo is broken, it becomes much easier to keep up with what is working and not working in your sexual life. 
There is a unique intimacy that comes during our sexual experiences and it is what most people crave as they turn each other on and get turned on. It is a unique way to see our partner and to be seen by our partner. In sum, we want to feel fulfilled sexually both as a giver and receiver of that intimate pleasure.", :need_group_id=> ng3.id, :oneliner=>"The need to be sexually satisfied")

#
#  Test Keywords
#
NeedsKeyword.delete_all
NeedsKeyword.create(:need_id=>n1.id, :keyword=>"admiration")
NeedsKeyword.create(:need_id=>n1.id, :keyword=>"unappreciated")
NeedsKeyword.create(:need_id=>n1.id, :keyword=>"ungrateful")
NeedsKeyword.create(:need_id=>n1.id, :keyword=>"unthankful")
NeedsKeyword.create(:need_id=>n1.id, :keyword=>"unappreciative")
NeedsKeyword.create(:need_id=>n1.id, :keyword=>"granted")
NeedsKeyword.create(:need_id=>n1.id, :keyword=>"appreciate")
NeedsKeyword.create(:need_id=>n1.id, :keyword=>"appreciation")
NeedsKeyword.create(:need_id=>n1.id, :keyword=>"irritating")
NeedsKeyword.create(:need_id=>n1.id, :keyword=>"annoying")
NeedsKeyword.create(:need_id=>n1.id, :keyword=>"nerves")
NeedsKeyword.create(:need_id=>n1.id, :keyword=>"aggravate")
NeedsKeyword.create(:need_id=>n1.id, :keyword=>"infuriate")
NeedsKeyword.create(:need_id=>n1.id, :keyword=>"bother")
NeedsKeyword.create(:need_id=>n1.id, :keyword=>"exasperate")
NeedsKeyword.create(:need_id=>n1.id, :keyword=>"exasperated")
NeedsKeyword.create(:need_id=>n1.id, :keyword=>"critical")
NeedsKeyword.create(:need_id=>n1.id, :keyword=>"critique")
NeedsKeyword.create(:need_id=>n1.id, :keyword=>"admires")
NeedsKeyword.create(:need_id=>n1.id, :keyword=>"nags")
NeedsKeyword.create(:need_id=>n1.id, :keyword=>"down")

NeedsKeyword.create(:need_id=>n2.id, :keyword=>"acceptance")
NeedsKeyword.create(:need_id=>n2.id, :keyword=>"distant")
NeedsKeyword.create(:need_id=>n2.id, :keyword=>"manipulates")
NeedsKeyword.create(:need_id=>n2.id, :keyword=>"manipulative")
NeedsKeyword.create(:need_id=>n2.id, :keyword=>"guilt")
NeedsKeyword.create(:need_id=>n2.id, :keyword=>"critical")
NeedsKeyword.create(:need_id=>n2.id, :keyword=>"critique")
NeedsKeyword.create(:need_id=>n2.id, :keyword=>"shames")
NeedsKeyword.create(:need_id=>n2.id, :keyword=>"nags")
NeedsKeyword.create(:need_id=>n2.id, :keyword=>"irritating")
NeedsKeyword.create(:need_id=>n2.id, :keyword=>"annoying")
NeedsKeyword.create(:need_id=>n2.id, :keyword=>"nerves")
NeedsKeyword.create(:need_id=>n2.id, :keyword=>"aggravate")
NeedsKeyword.create(:need_id=>n2.id, :keyword=>"infuriate")
NeedsKeyword.create(:need_id=>n2.id, :keyword=>"bother")
NeedsKeyword.create(:need_id=>n2.id, :keyword=>"exasperate")
NeedsKeyword.create(:need_id=>n2.id, :keyword=>"exasperated")
NeedsKeyword.create(:need_id=>n2.id, :keyword=>"nagging")
NeedsKeyword.create(:need_id=>n2.id, :keyword=>"irritating")
NeedsKeyword.create(:need_id=>n2.id, :keyword=>"harassing")
NeedsKeyword.create(:need_id=>n2.id, :keyword=>"critical")
NeedsKeyword.create(:need_id=>n2.id, :keyword=>"critique")
NeedsKeyword.create(:need_id=>n2.id, :keyword=>"admires")
NeedsKeyword.create(:need_id=>n2.id, :keyword=>"nags")
NeedsKeyword.create(:need_id=>n2.id, :keyword=>"down")
NeedsKeyword.create(:need_id=>n2.id, :keyword=>"controlling")
NeedsKeyword.create(:need_id=>n2.id, :keyword=>"stifled")
NeedsKeyword.create(:need_id=>n2.id, :keyword=>"lonely")
NeedsKeyword.create(:need_id=>n2.id, :keyword=>"micromanager")
NeedsKeyword.create(:need_id=>n2.id, :keyword=>"micromanages")
NeedsKeyword.create(:need_id=>n2.id, :keyword=>"control")
NeedsKeyword.create(:need_id=>n2.id, :keyword=>"runs")
NeedsKeyword.create(:need_id=>n2.id, :keyword=>"running")
NeedsKeyword.create(:need_id=>n2.id, :keyword=>"control")
NeedsKeyword.create(:need_id=>n2.id, :keyword=>"freak")
NeedsKeyword.create(:need_id=>n2.id, :keyword=>"change")
NeedsKeyword.create(:need_id=>n2.id, :keyword=>"accept")
NeedsKeyword.create(:need_id=>n2.id, :keyword=>"changing")
NeedsKeyword.create(:need_id=>n2.id, :keyword=>"enough")

NeedsKeyword.create(:need_id=>n3.id, :keyword=>"appreciation")
NeedsKeyword.create(:need_id=>n3.id, :keyword=>"intimacy")
NeedsKeyword.create(:need_id=>n3.id, :keyword=>"emotional")
NeedsKeyword.create(:need_id=>n3.id, :keyword=>"bond")
NeedsKeyword.create(:need_id=>n3.id, :keyword=>"closeness")
NeedsKeyword.create(:need_id=>n3.id, :keyword=>"familiarity")
NeedsKeyword.create(:need_id=>n3.id, :keyword=>"understanding")
NeedsKeyword.create(:need_id=>n3.id, :keyword=>"confidence")
NeedsKeyword.create(:need_id=>n3.id, :keyword=>"caring")
NeedsKeyword.create(:need_id=>n3.id, :keyword=>"tenderness")
NeedsKeyword.create(:need_id=>n3.id, :keyword=>"affectionate")
NeedsKeyword.create(:need_id=>n3.id, :keyword=>"unappreciated")
NeedsKeyword.create(:need_id=>n3.id, :keyword=>"ungrateful")
NeedsKeyword.create(:need_id=>n3.id, :keyword=>"unthankful")
NeedsKeyword.create(:need_id=>n3.id, :keyword=>"unappreciative")
NeedsKeyword.create(:need_id=>n3.id, :keyword=>"granted")
NeedsKeyword.create(:need_id=>n3.id, :keyword=>"appreciate")
NeedsKeyword.create(:need_id=>n3.id, :keyword=>"appreciation")
NeedsKeyword.create(:need_id=>n3.id, :keyword=>"needy")
NeedsKeyword.create(:need_id=>n3.id, :keyword=>"unloved")
NeedsKeyword.create(:need_id=>n3.id, :keyword=>"disinterested")
NeedsKeyword.create(:need_id=>n3.id, :keyword=>"cold")
NeedsKeyword.create(:need_id=>n3.id, :keyword=>"distant")


NeedsKeyword.create(:need_id=>n4.id, :keyword=>"autonomy")
NeedsKeyword.create(:need_id=>n4.id, :keyword=>"critical")
NeedsKeyword.create(:need_id=>n4.id, :keyword=>"critique")
NeedsKeyword.create(:need_id=>n4.id, :keyword=>"admires")
NeedsKeyword.create(:need_id=>n4.id, :keyword=>"nags")
NeedsKeyword.create(:need_id=>n4.id, :keyword=>"case")
NeedsKeyword.create(:need_id=>n4.id, :keyword=>"irritating")
NeedsKeyword.create(:need_id=>n4.id, :keyword=>"annoying")
NeedsKeyword.create(:need_id=>n4.id, :keyword=>"nerves")
NeedsKeyword.create(:need_id=>n4.id, :keyword=>"aggravate")
NeedsKeyword.create(:need_id=>n4.id, :keyword=>"infuriate")
NeedsKeyword.create(:need_id=>n4.id, :keyword=>"bother")
NeedsKeyword.create(:need_id=>n4.id, :keyword=>"exasperate")
NeedsKeyword.create(:need_id=>n4.id, :keyword=>"exasperated")
NeedsKeyword.create(:need_id=>n4.id, :keyword=>"annoying")
NeedsKeyword.create(:need_id=>n4.id, :keyword=>"upsetting")
NeedsKeyword.create(:need_id=>n4.id, :keyword=>"upset")
NeedsKeyword.create(:need_id=>n4.id, :keyword=>"deliberately")
NeedsKeyword.create(:need_id=>n4.id, :keyword=>"annoy")
NeedsKeyword.create(:need_id=>n4.id, :keyword=>"critical")
NeedsKeyword.create(:need_id=>n4.id, :keyword=>"critique")
NeedsKeyword.create(:need_id=>n4.id, :keyword=>"admires")
NeedsKeyword.create(:need_id=>n4.id, :keyword=>"nags")
NeedsKeyword.create(:need_id=>n4.id, :keyword=>"down")
NeedsKeyword.create(:need_id=>n4.id, :keyword=>"puts")
NeedsKeyword.create(:need_id=>n4.id, :keyword=>"nagging")
NeedsKeyword.create(:need_id=>n4.id, :keyword=>"harassing")
NeedsKeyword.create(:need_id=>n4.id, :keyword=>"irritating")
NeedsKeyword.create(:need_id=>n4.id, :keyword=>"change")
NeedsKeyword.create(:need_id=>n4.id, :keyword=>"accept")
NeedsKeyword.create(:need_id=>n4.id, :keyword=>"changing")
NeedsKeyword.create(:need_id=>n4.id, :keyword=>"enough")
NeedsKeyword.create(:need_id=>n4.id, :keyword=>"distant")
NeedsKeyword.create(:need_id=>n4.id, :keyword=>"manipulates")
NeedsKeyword.create(:need_id=>n4.id, :keyword=>"manipulative")
NeedsKeyword.create(:need_id=>n4.id, :keyword=>"guilt")
NeedsKeyword.create(:need_id=>n4.id, :keyword=>"controlling")
NeedsKeyword.create(:need_id=>n4.id, :keyword=>"rule")
NeedsKeyword.create(:need_id=>n4.id, :keyword=>"domineering")
NeedsKeyword.create(:need_id=>n4.id, :keyword=>"dominates")
NeedsKeyword.create(:need_id=>n4.id, :keyword=>"pushes")
NeedsKeyword.create(:need_id=>n4.id, :keyword=>"pushy")
NeedsKeyword.create(:need_id=>n4.id, :keyword=>"nags")
NeedsKeyword.create(:need_id=>n4.id, :keyword=>"nagging")


NeedsKeyword.create(:need_id=>n5.id, :keyword=>"known")
NeedsKeyword.create(:need_id=>n5.id, :keyword=>"forget")
NeedsKeyword.create(:need_id=>n5.id, :keyword=>"disregard")
NeedsKeyword.create(:need_id=>n5.id, :keyword=>"fail")
NeedsKeyword.create(:need_id=>n5.id, :keyword=>"remember")
NeedsKeyword.create(:need_id=>n5.id, :keyword=>"overlook")

NeedsKeyword.create(:need_id=>n6.id, :keyword=>"respect")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"pass")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"gas")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"burp")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"blech")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"slob")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"messy")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"embarrasses")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"embarrasment")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"stare")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"gaze")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"gape")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"gawk")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"women")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"other")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"men")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"flirts")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"fools")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"annoying")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"upsetting")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"upset")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"deliberately")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"annoy")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"irritating")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"habit")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"habits")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"clean")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"messy")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"dirty")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"filthy")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"slob")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"untidy")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"sloppy")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"filthy")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"dirty")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"yelling")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"shout")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"scream")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"avoidance")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"evasive")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"stonewalls")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"stonewalling")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"shuts")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"down")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"flirts")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"comes")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"ignores")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"fooling")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"fools")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"critical")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"critique")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"admires")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"nags")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"puts")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"down")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"unfaithful")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"affair")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"cheating")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"extra")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"marital")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"fucking")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"staying")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"late")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"comes")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"homes")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"act")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"public")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"manners")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"social")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"moron")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"embarrassing")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"embarrasment")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"embarasing")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"embarasment")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"etiquette")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"doesn't")
NeedsKeyword.create(:need_id=>n6.id, :keyword=>"seriously")


NeedsKeyword.create(:need_id=>n7.id, :keyword=>"connection")
NeedsKeyword.create(:need_id=>n7.id, :keyword=>"concern")
NeedsKeyword.create(:need_id=>n7.id, :keyword=>"love")
NeedsKeyword.create(:need_id=>n7.id, :keyword=>"connect")
NeedsKeyword.create(:need_id=>n7.id, :keyword=>"connected")
NeedsKeyword.create(:need_id=>n7.id, :keyword=>"devoted")
NeedsKeyword.create(:need_id=>n7.id, :keyword=>"devotion")
NeedsKeyword.create(:need_id=>n7.id, :keyword=>"lack")
NeedsKeyword.create(:need_id=>n7.id, :keyword=>"intimacy")
NeedsKeyword.create(:need_id=>n7.id, :keyword=>"cold")
NeedsKeyword.create(:need_id=>n7.id, :keyword=>"distant")
NeedsKeyword.create(:need_id=>n7.id, :keyword=>"withdrawn")
NeedsKeyword.create(:need_id=>n7.id, :keyword=>"another")
NeedsKeyword.create(:need_id=>n7.id, :keyword=>"person")
NeedsKeyword.create(:need_id=>n7.id, :keyword=>"roommate")
NeedsKeyword.create(:need_id=>n7.id, :keyword=>"person")
NeedsKeyword.create(:need_id=>n7.id, :keyword=>"woman")
NeedsKeyword.create(:need_id=>n7.id, :keyword=>"man")
NeedsKeyword.create(:need_id=>n7.id, :keyword=>"completely")
NeedsKeyword.create(:need_id=>n7.id, :keyword=>"changed")


NeedsKeyword.create(:need_id=>n8.id, :keyword=>"communication")
NeedsKeyword.create(:need_id=>n8.id, :keyword=>"cooperation")
NeedsKeyword.create(:need_id=>n8.id, :keyword=>"collaboration")
NeedsKeyword.create(:need_id=>n8.id, :keyword=>"lack")
NeedsKeyword.create(:need_id=>n8.id, :keyword=>"teamwork")
NeedsKeyword.create(:need_id=>n8.id, :keyword=>"joint")
NeedsKeyword.create(:need_id=>n8.id, :keyword=>"effort")
NeedsKeyword.create(:need_id=>n8.id, :keyword=>"solidarity")
NeedsKeyword.create(:need_id=>n8.id, :keyword=>"silent")
NeedsKeyword.create(:need_id=>n8.id, :keyword=>"treatment")
NeedsKeyword.create(:need_id=>n8.id, :keyword=>"refuse")
NeedsKeyword.create(:need_id=>n8.id, :keyword=>"talk")
NeedsKeyword.create(:need_id=>n8.id, :keyword=>"silence")
NeedsKeyword.create(:need_id=>n8.id, :keyword=>"talking")
NeedsKeyword.create(:need_id=>n8.id, :keyword=>"poor")
NeedsKeyword.create(:need_id=>n8.id, :keyword=>"converse")
NeedsKeyword.create(:need_id=>n8.id, :keyword=>"chat")
NeedsKeyword.create(:need_id=>n8.id, :keyword=>"speak")
NeedsKeyword.create(:need_id=>n8.id, :keyword=>"communicate")
NeedsKeyword.create(:need_id=>n8.id, :keyword=>"connect")
NeedsKeyword.create(:need_id=>n8.id, :keyword=>"relate")
NeedsKeyword.create(:need_id=>n8.id, :keyword=>"conversation")
NeedsKeyword.create(:need_id=>n8.id, :keyword=>"conversations")
NeedsKeyword.create(:need_id=>n8.id, :keyword=>"superficial")
NeedsKeyword.create(:need_id=>n8.id, :keyword=>"yelling")
NeedsKeyword.create(:need_id=>n8.id, :keyword=>"shout")
NeedsKeyword.create(:need_id=>n8.id, :keyword=>"scream")
NeedsKeyword.create(:need_id=>n8.id, :keyword=>"avoidance")
NeedsKeyword.create(:need_id=>n8.id, :keyword=>"evasive")
NeedsKeyword.create(:need_id=>n8.id, :keyword=>"stonewalling")
NeedsKeyword.create(:need_id=>n8.id, :keyword=>"stonewalls")
NeedsKeyword.create(:need_id=>n8.id, :keyword=>"shuts")
NeedsKeyword.create(:need_id=>n8.id, :keyword=>"doesn't")
NeedsKeyword.create(:need_id=>n8.id, :keyword=>"take")
NeedsKeyword.create(:need_id=>n8.id, :keyword=>"seriously")
NeedsKeyword.create(:need_id=>n8.id, :keyword=>"respect")
NeedsKeyword.create(:need_id=>n8.id, :keyword=>"insensitive")
NeedsKeyword.create(:need_id=>n8.id, :keyword=>"uncompassionate")
NeedsKeyword.create(:need_id=>n8.id, :keyword=>"speak")
NeedsKeyword.create(:need_id=>n8.id, :keyword=>"can't")
NeedsKeyword.create(:need_id=>n8.id, :keyword=>"communicate")
NeedsKeyword.create(:need_id=>n8.id, :keyword=>"feelings")
NeedsKeyword.create(:need_id=>n8.id, :keyword=>"needs")
NeedsKeyword.create(:need_id=>n8.id, :keyword=>"feel")
NeedsKeyword.create(:need_id=>n8.id, :keyword=>"understand")

NeedsKeyword.create(:need_id=>n9.id, :keyword=>"common")
NeedsKeyword.create(:need_id=>n9.id, :keyword=>"higher")
NeedsKeyword.create(:need_id=>n9.id, :keyword=>"purpose")
NeedsKeyword.create(:need_id=>n9.id, :keyword=>"different")
NeedsKeyword.create(:need_id=>n9.id, :keyword=>"goals")
NeedsKeyword.create(:need_id=>n9.id, :keyword=>"dreams")
NeedsKeyword.create(:need_id=>n9.id, :keyword=>"aspirations")
NeedsKeyword.create(:need_id=>n9.id, :keyword=>"ambition")
NeedsKeyword.create(:need_id=>n9.id, :keyword=>"purpose")
NeedsKeyword.create(:need_id=>n9.id, :keyword=>"philosophy")
NeedsKeyword.create(:need_id=>n9.id, :keyword=>"unambitious")
NeedsKeyword.create(:need_id=>n9.id, :keyword=>"pride")
NeedsKeyword.create(:need_id=>n9.id, :keyword=>"aimless")
NeedsKeyword.create(:need_id=>n9.id, :keyword=>"direction")
NeedsKeyword.create(:need_id=>n9.id, :keyword=>"lazy")
NeedsKeyword.create(:need_id=>n9.id, :keyword=>"lies")
NeedsKeyword.create(:need_id=>n9.id, :keyword=>"depressed")
NeedsKeyword.create(:need_id=>n9.id, :keyword=>"sleeps")
NeedsKeyword.create(:need_id=>n9.id, :keyword=>"doesn't")
NeedsKeyword.create(:need_id=>n9.id, :keyword=>"work")
NeedsKeyword.create(:need_id=>n9.id, :keyword=>"couch")
NeedsKeyword.create(:need_id=>n9.id, :keyword=>"slacker")
NeedsKeyword.create(:need_id=>n9.id, :keyword=>"lays")
NeedsKeyword.create(:need_id=>n9.id, :keyword=>"bed")

NeedsKeyword.create(:need_id=>n10.id, :keyword=>"domestic")
NeedsKeyword.create(:need_id=>n10.id, :keyword=>"financial")
NeedsKeyword.create(:need_id=>n10.id, :keyword=>"support")
NeedsKeyword.create(:need_id=>n10.id, :keyword=>"unambitious")
NeedsKeyword.create(:need_id=>n10.id, :keyword=>"goals")
NeedsKeyword.create(:need_id=>n10.id, :keyword=>"pride")
NeedsKeyword.create(:need_id=>n10.id, :keyword=>"aimless")
NeedsKeyword.create(:need_id=>n10.id, :keyword=>"direction")
NeedsKeyword.create(:need_id=>n10.id, :keyword=>"lazy")
NeedsKeyword.create(:need_id=>n10.id, :keyword=>"lies")
NeedsKeyword.create(:need_id=>n10.id, :keyword=>"depressed")
NeedsKeyword.create(:need_id=>n10.id, :keyword=>"unemployed")
NeedsKeyword.create(:need_id=>n10.id, :keyword=>"jobless")
NeedsKeyword.create(:need_id=>n10.id, :keyword=>"bum")
NeedsKeyword.create(:need_id=>n10.id, :keyword=>"slacker")
NeedsKeyword.create(:need_id=>n10.id, :keyword=>"lays")
NeedsKeyword.create(:need_id=>n10.id, :keyword=>"lies")
NeedsKeyword.create(:need_id=>n10.id, :keyword=>"couch")
NeedsKeyword.create(:need_id=>n10.id, :keyword=>"tv")
NeedsKeyword.create(:need_id=>n10.id, :keyword=>"debt")
NeedsKeyword.create(:need_id=>n10.id, :keyword=>"bills")
NeedsKeyword.create(:need_id=>n10.id, :keyword=>"card")
NeedsKeyword.create(:need_id=>n10.id, :keyword=>"payments")
NeedsKeyword.create(:need_id=>n10.id, :keyword=>"spends")
NeedsKeyword.create(:need_id=>n10.id, :keyword=>"buys")
NeedsKeyword.create(:need_id=>n10.id, :keyword=>"shopping")
NeedsKeyword.create(:need_id=>n10.id, :keyword=>"shopaholic")
NeedsKeyword.create(:need_id=>n10.id, :keyword=>"spendthrift")
NeedsKeyword.create(:need_id=>n10.id, :keyword=>"cheap")
NeedsKeyword.create(:need_id=>n10.id, :keyword=>"tightwad")


NeedsKeyword.create(:need_id=>n11.id, :keyword=>"family")
NeedsKeyword.create(:need_id=>n11.id, :keyword=>"commitment")
NeedsKeyword.create(:need_id=>n11.id, :keyword=>"lazy")
NeedsKeyword.create(:need_id=>n11.id, :keyword=>"chores")
NeedsKeyword.create(:need_id=>n11.id, :keyword=>"house")
NeedsKeyword.create(:need_id=>n11.id, :keyword=>"helpful")
NeedsKeyword.create(:need_id=>n11.id, :keyword=>"kids")
NeedsKeyword.create(:need_id=>n11.id, :keyword=>"time")
NeedsKeyword.create(:need_id=>n11.id, :keyword=>"away")
NeedsKeyword.create(:need_id=>n11.id, :keyword=>"apart")
NeedsKeyword.create(:need_id=>n11.id, :keyword=>"space")
NeedsKeyword.create(:need_id=>n11.id, :keyword=>"traveling")
NeedsKeyword.create(:need_id=>n11.id, :keyword=>"workaholic")
NeedsKeyword.create(:need_id=>n11.id, :keyword=>"career")
NeedsKeyword.create(:need_id=>n11.id, :keyword=>"occupation")
NeedsKeyword.create(:need_id=>n11.id, :keyword=>"work")
NeedsKeyword.create(:need_id=>n11.id, :keyword=>"profession")
NeedsKeyword.create(:need_id=>n11.id, :keyword=>"trade")
NeedsKeyword.create(:need_id=>n11.id, :keyword=>"employment")
NeedsKeyword.create(:need_id=>n11.id, :keyword=>"post")
NeedsKeyword.create(:need_id=>n11.id, :keyword=>"situation")
NeedsKeyword.create(:need_id=>n11.id, :keyword=>"lazy")
NeedsKeyword.create(:need_id=>n11.id, :keyword=>"depressed")
NeedsKeyword.create(:need_id=>n11.id, :keyword=>"tv")
NeedsKeyword.create(:need_id=>n11.id, :keyword=>"watches")
NeedsKeyword.create(:need_id=>n11.id, :keyword=>"watching")
NeedsKeyword.create(:need_id=>n11.id, :keyword=>"lays")
NeedsKeyword.create(:need_id=>n11.id, :keyword=>"job")
NeedsKeyword.create(:need_id=>n11.id, :keyword=>"in-laws")
NeedsKeyword.create(:need_id=>n11.id, :keyword=>"brother-in-law")
NeedsKeyword.create(:need_id=>n11.id, :keyword=>"brother")
NeedsKeyword.create(:need_id=>n11.id, :keyword=>"sister")
NeedsKeyword.create(:need_id=>n11.id, :keyword=>"sister-in-law")
NeedsKeyword.create(:need_id=>n11.id, :keyword=>"mother")
NeedsKeyword.create(:need_id=>n11.id, :keyword=>"mother-in-law")
NeedsKeyword.create(:need_id=>n11.id, :keyword=>"father")
NeedsKeyword.create(:need_id=>n11.id, :keyword=>"father-in-law")
NeedsKeyword.create(:need_id=>n11.id, :keyword=>"husband")
NeedsKeyword.create(:need_id=>n11.id, :keyword=>"husband's")
NeedsKeyword.create(:need_id=>n11.id, :keyword=>"alcoholic")
NeedsKeyword.create(:need_id=>n11.id, :keyword=>"drinks")
NeedsKeyword.create(:need_id=>n11.id, :keyword=>"booze")
NeedsKeyword.create(:need_id=>n11.id, :keyword=>"drugs")
NeedsKeyword.create(:need_id=>n11.id, :keyword=>"cocaine")
NeedsKeyword.create(:need_id=>n11.id, :keyword=>"meth")
NeedsKeyword.create(:need_id=>n11.id, :keyword=>"alcohol")
NeedsKeyword.create(:need_id=>n11.id, :keyword=>"addict")



NeedsKeyword.create(:need_id=>n12.id, :keyword=>"devotion")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"inlaws")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"father")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"mother")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"influenced")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"relatives")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"in-laws")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"brother-in-law")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"brother")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"sister")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"sister-in-law")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"mother")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"mother-in-law")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"father")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"father-in-law")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"husband")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"husband's")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"annoying")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"upset")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"upsetting")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"deliberately")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"annoy")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"needy")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"unloved")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"disinterested")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"cold")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"distant")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"flirts")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"ignores")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"fooling")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"fools")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"unfaithful")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"affair")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"cheating")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"extra")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"marital")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"fucking")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"staying")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"late")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"home")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"person")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"woman")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"man")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"completely")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"changed")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"love")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"connect")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"connected")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"devoted")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"devotion")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"bored")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"growing")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"intellectual")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"stimulation")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"intellectually")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"stimulating")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"spiritual")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"growth")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"developing")
NeedsKeyword.create(:need_id=>n12.id, :keyword=>"myself")

NeedsKeyword.create(:need_id=>n13.id, :keyword=>"honesty")

NeedsKeyword.create(:need_id=>n14.id, :keyword=>"affection")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"needy")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"unloved")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"disinterested")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"cold")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"distant")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"tired")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"worn")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"weary")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"fatigue")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"drain")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"roommate")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"housemate")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"flat")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"mate")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"wall")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"roommates")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"hardly")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"talk")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"time")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"away")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"apart")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"spave")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"traveling")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"workaholic")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"career")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"occupation")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"work")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"profession")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"trade")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"employment")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"post")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"situation")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"intimacy")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"lack")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"withdrawn")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"person")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"intimacy")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"emotional")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"bond")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"closeness")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"familiarity")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"understanding")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"confidence")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"caring")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"tenderness")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"affectionate")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"silent")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"treatment")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"refuse")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"talk")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"silence")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"talking")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"sex")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"intercouse")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"fuck")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"sexually")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"frustrated")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"fat")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"attractive")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"tired")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"worn")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"weary")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"fatigue")
NeedsKeyword.create(:need_id=>n14.id, :keyword=>"drain")

NeedsKeyword.create(:need_id=>n15.id, :keyword=>"personal")
NeedsKeyword.create(:need_id=>n15.id, :keyword=>"growth")
NeedsKeyword.create(:need_id=>n15.id, :keyword=>"stimulation")
NeedsKeyword.create(:need_id=>n15.id, :keyword=>"bored")
NeedsKeyword.create(:need_id=>n15.id, :keyword=>"growing")
NeedsKeyword.create(:need_id=>n15.id, :keyword=>"intellectual")
NeedsKeyword.create(:need_id=>n15.id, :keyword=>"stimulating")
NeedsKeyword.create(:need_id=>n15.id, :keyword=>"spiritual")
NeedsKeyword.create(:need_id=>n15.id, :keyword=>"developing")
NeedsKeyword.create(:need_id=>n15.id, :keyword=>"myself")


NeedsKeyword.create(:need_id=>n16.id, :keyword=>"recreational")
NeedsKeyword.create(:need_id=>n16.id, :keyword=>"companionship")
NeedsKeyword.create(:need_id=>n16.id, :keyword=>"fun")
NeedsKeyword.create(:need_id=>n16.id, :keyword=>"together")
NeedsKeyword.create(:need_id=>n16.id, :keyword=>"rigid")
NeedsKeyword.create(:need_id=>n16.id, :keyword=>"stoic")
NeedsKeyword.create(:need_id=>n16.id, :keyword=>"stiff")
NeedsKeyword.create(:need_id=>n16.id, :keyword=>"stuck")
NeedsKeyword.create(:need_id=>n16.id, :keyword=>"serious")
NeedsKeyword.create(:need_id=>n16.id, :keyword=>"relax")
NeedsKeyword.create(:need_id=>n16.id, :keyword=>"uptight")
NeedsKeyword.create(:need_id=>n16.id, :keyword=>"play")
NeedsKeyword.create(:need_id=>n16.id, :keyword=>"go")
NeedsKeyword.create(:need_id=>n16.id, :keyword=>"out")
NeedsKeyword.create(:need_id=>n16.id, :keyword=>"roommate")
NeedsKeyword.create(:need_id=>n16.id, :keyword=>"housemate")
NeedsKeyword.create(:need_id=>n16.id, :keyword=>"flatmate")
NeedsKeyword.create(:need_id=>n16.id, :keyword=>"mate")
NeedsKeyword.create(:need_id=>n16.id, :keyword=>"wall")
NeedsKeyword.create(:need_id=>n16.id, :keyword=>"distant")
NeedsKeyword.create(:need_id=>n16.id, :keyword=>"cold")
NeedsKeyword.create(:need_id=>n16.id, :keyword=>"roommates")
NeedsKeyword.create(:need_id=>n16.id, :keyword=>"hardly")
NeedsKeyword.create(:need_id=>n16.id, :keyword=>"talk")
NeedsKeyword.create(:need_id=>n16.id, :keyword=>"free")
NeedsKeyword.create(:need_id=>n16.id, :keyword=>"leisure")
NeedsKeyword.create(:need_id=>n16.id, :keyword=>"spare")
NeedsKeyword.create(:need_id=>n16.id, :keyword=>"vacation")
NeedsKeyword.create(:need_id=>n16.id, :keyword=>"off")
NeedsKeyword.create(:need_id=>n16.id, :keyword=>"relaxation")
NeedsKeyword.create(:need_id=>n16.id, :keyword=>"bored")
NeedsKeyword.create(:need_id=>n16.id, :keyword=>"growing")
NeedsKeyword.create(:need_id=>n16.id, :keyword=>"intellectual")
NeedsKeyword.create(:need_id=>n16.id, :keyword=>"stimulating")
NeedsKeyword.create(:need_id=>n16.id, :keyword=>"stimulation")
NeedsKeyword.create(:need_id=>n16.id, :keyword=>"intellectually")
NeedsKeyword.create(:need_id=>n16.id, :keyword=>"spiritual")
NeedsKeyword.create(:need_id=>n16.id, :keyword=>"growing")
NeedsKeyword.create(:need_id=>n16.id, :keyword=>"developing")
NeedsKeyword.create(:need_id=>n16.id, :keyword=>"myself")
NeedsKeyword.create(:need_id=>n16.id, :keyword=>"growth")

NeedsKeyword.create(:need_id=>n17.id, :keyword=>"contribute")

NeedsKeyword.create(:need_id=>n18.id, :keyword=>"trust")
NeedsKeyword.create(:need_id=>n18.id, :keyword=>"shopaholic")
NeedsKeyword.create(:need_id=>n18.id, :keyword=>"spendthrift")
NeedsKeyword.create(:need_id=>n18.id, :keyword=>"cheap")
NeedsKeyword.create(:need_id=>n18.id, :keyword=>"tightwad")
NeedsKeyword.create(:need_id=>n18.id, :keyword=>"distant")
NeedsKeyword.create(:need_id=>n18.id, :keyword=>"past")
NeedsKeyword.create(:need_id=>n18.id, :keyword=>"manipulates")
NeedsKeyword.create(:need_id=>n18.id, :keyword=>"manipulative")
NeedsKeyword.create(:need_id=>n18.id, :keyword=>"guilt")
NeedsKeyword.create(:need_id=>n18.id, :keyword=>"trip")
NeedsKeyword.create(:need_id=>n18.id, :keyword=>"stare")
NeedsKeyword.create(:need_id=>n18.id, :keyword=>"gaze")
NeedsKeyword.create(:need_id=>n18.id, :keyword=>"gape")
NeedsKeyword.create(:need_id=>n18.id, :keyword=>"gawk")
NeedsKeyword.create(:need_id=>n18.id, :keyword=>"woman")
NeedsKeyword.create(:need_id=>n18.id, :keyword=>"man")
NeedsKeyword.create(:need_id=>n18.id, :keyword=>"flirts")
NeedsKeyword.create(:need_id=>n18.id, :keyword=>"fools")
NeedsKeyword.create(:need_id=>n18.id, :keyword=>"hits")
NeedsKeyword.create(:need_id=>n18.id, :keyword=>"physically")
NeedsKeyword.create(:need_id=>n18.id, :keyword=>"threatens")
NeedsKeyword.create(:need_id=>n18.id, :keyword=>"abusive")
NeedsKeyword.create(:need_id=>n18.id, :keyword=>"abuse")
NeedsKeyword.create(:need_id=>n18.id, :keyword=>"mistreatment")
NeedsKeyword.create(:need_id=>n18.id, :keyword=>"mistreats")
NeedsKeyword.create(:need_id=>n18.id, :keyword=>"violent")
NeedsKeyword.create(:need_id=>n18.id, :keyword=>"violence")
NeedsKeyword.create(:need_id=>n18.id, :keyword=>"maltreatment")
NeedsKeyword.create(:need_id=>n18.id, :keyword=>"cruelty")
NeedsKeyword.create(:need_id=>n18.id, :keyword=>"flirts")
NeedsKeyword.create(:need_id=>n18.id, :keyword=>"ignores")
NeedsKeyword.create(:need_id=>n18.id, :keyword=>"fooling")
NeedsKeyword.create(:need_id=>n18.id, :keyword=>"fools")
NeedsKeyword.create(:need_id=>n18.id, :keyword=>"unfaithful")
NeedsKeyword.create(:need_id=>n18.id, :keyword=>"affair")
NeedsKeyword.create(:need_id=>n18.id, :keyword=>"cheating")
NeedsKeyword.create(:need_id=>n18.id, :keyword=>"extra")
NeedsKeyword.create(:need_id=>n18.id, :keyword=>"marital")
NeedsKeyword.create(:need_id=>n18.id, :keyword=>"fucking")
NeedsKeyword.create(:need_id=>n18.id, :keyword=>"staying")
NeedsKeyword.create(:need_id=>n18.id, :keyword=>"late")
NeedsKeyword.create(:need_id=>n18.id, :keyword=>"comes")
NeedsKeyword.create(:need_id=>n18.id, :keyword=>"home")
NeedsKeyword.create(:need_id=>n18.id, :keyword=>"unambitious")
NeedsKeyword.create(:need_id=>n18.id, :keyword=>"goals")
NeedsKeyword.create(:need_id=>n18.id, :keyword=>"pride")
NeedsKeyword.create(:need_id=>n18.id, :keyword=>"aimless")
NeedsKeyword.create(:need_id=>n18.id, :keyword=>"direction")
NeedsKeyword.create(:need_id=>n18.id, :keyword=>"lazy")
NeedsKeyword.create(:need_id=>n18.id, :keyword=>"lies")
NeedsKeyword.create(:need_id=>n18.id, :keyword=>"depressed")


NeedsKeyword.create(:need_id=>n19.id, :keyword=>"trusted")
NeedsKeyword.create(:need_id=>n19.id, :keyword=>"lack")
NeedsKeyword.create(:need_id=>n19.id, :keyword=>"trust")
NeedsKeyword.create(:need_id=>n19.id, :keyword=>"insecure")
NeedsKeyword.create(:need_id=>n19.id, :keyword=>"insecurity")
NeedsKeyword.create(:need_id=>n19.id, :keyword=>"checkbook")


NeedsKeyword.create(:need_id=>n20.id, :keyword=>"understanding")
NeedsKeyword.create(:need_id=>n20.id, :keyword=>"fight")
NeedsKeyword.create(:need_id=>n20.id, :keyword=>"argue")
NeedsKeyword.create(:need_id=>n20.id, :keyword=>"arguing")
NeedsKeyword.create(:need_id=>n20.id, :keyword=>"quarrel")
NeedsKeyword.create(:need_id=>n20.id, :keyword=>"quarrelling")
NeedsKeyword.create(:need_id=>n20.id, :keyword=>"blows")
NeedsKeyword.create(:need_id=>n20.id, :keyword=>"yelling")
NeedsKeyword.create(:need_id=>n20.id, :keyword=>"intimacy")
NeedsKeyword.create(:need_id=>n20.id, :keyword=>"emotional")
NeedsKeyword.create(:need_id=>n20.id, :keyword=>"bond")
NeedsKeyword.create(:need_id=>n20.id, :keyword=>"closeness")
NeedsKeyword.create(:need_id=>n20.id, :keyword=>"familiarity")
NeedsKeyword.create(:need_id=>n20.id, :keyword=>"understanding")
NeedsKeyword.create(:need_id=>n20.id, :keyword=>"confidence")
NeedsKeyword.create(:need_id=>n20.id, :keyword=>"caring")
NeedsKeyword.create(:need_id=>n20.id, :keyword=>"tenderness")
NeedsKeyword.create(:need_id=>n20.id, :keyword=>"affectionate")
NeedsKeyword.create(:need_id=>n20.id, :keyword=>"critical")
NeedsKeyword.create(:need_id=>n20.id, :keyword=>"critique")
NeedsKeyword.create(:need_id=>n20.id, :keyword=>"admires")
NeedsKeyword.create(:need_id=>n20.id, :keyword=>"nags")
NeedsKeyword.create(:need_id=>n20.id, :keyword=>"puts")
NeedsKeyword.create(:need_id=>n20.id, :keyword=>"down")

NeedsKeyword.create(:need_id=>n21.id, :keyword=>"reciprocity")
NeedsKeyword.create(:need_id=>n21.id, :keyword=>"stubborn")
NeedsKeyword.create(:need_id=>n21.id, :keyword=>"strong")
NeedsKeyword.create(:need_id=>n21.id, :keyword=>"headed")
NeedsKeyword.create(:need_id=>n21.id, :keyword=>"inflexible")
NeedsKeyword.create(:need_id=>n21.id, :keyword=>"doormant")
NeedsKeyword.create(:need_id=>n21.id, :keyword=>"granted")
NeedsKeyword.create(:need_id=>n21.id, :keyword=>"taken")
NeedsKeyword.create(:need_id=>n21.id, :keyword=>"used")
NeedsKeyword.create(:need_id=>n21.id, :keyword=>"advantage")
NeedsKeyword.create(:need_id=>n21.id, :keyword=>"exploited")
NeedsKeyword.create(:need_id=>n21.id, :keyword=>"over")


NeedsKeyword.create(:need_id=>n22.id, :keyword=>"safety")
NeedsKeyword.create(:need_id=>n22.id, :keyword=>"hits")
NeedsKeyword.create(:need_id=>n22.id, :keyword=>"physically")
NeedsKeyword.create(:need_id=>n22.id, :keyword=>"threatens")
NeedsKeyword.create(:need_id=>n22.id, :keyword=>"abuse")
NeedsKeyword.create(:need_id=>n22.id, :keyword=>"abusive")
NeedsKeyword.create(:need_id=>n22.id, :keyword=>"mistreatment")
NeedsKeyword.create(:need_id=>n22.id, :keyword=>"mistreats")
NeedsKeyword.create(:need_id=>n22.id, :keyword=>"violent")
NeedsKeyword.create(:need_id=>n22.id, :keyword=>"violence")
NeedsKeyword.create(:need_id=>n22.id, :keyword=>"maltreatment")
NeedsKeyword.create(:need_id=>n22.id, :keyword=>"cruelty")
NeedsKeyword.create(:need_id=>n22.id, :keyword=>"flirts")
NeedsKeyword.create(:need_id=>n22.id, :keyword=>"ignores")
NeedsKeyword.create(:need_id=>n22.id, :keyword=>"fooling")
NeedsKeyword.create(:need_id=>n22.id, :keyword=>"fools")
NeedsKeyword.create(:need_id=>n22.id, :keyword=>"alcohol")
NeedsKeyword.create(:need_id=>n22.id, :keyword=>"alcoholic")
NeedsKeyword.create(:need_id=>n22.id, :keyword=>"drinks")
NeedsKeyword.create(:need_id=>n22.id, :keyword=>"booze")
NeedsKeyword.create(:need_id=>n22.id, :keyword=>"drugs")
NeedsKeyword.create(:need_id=>n22.id, :keyword=>"cocaine")
NeedsKeyword.create(:need_id=>n22.id, :keyword=>"meth")
NeedsKeyword.create(:need_id=>n22.id, :keyword=>"addict")


NeedsKeyword.create(:need_id=>n23.id, :keyword=>"openness")
NeedsKeyword.create(:need_id=>n23.id, :keyword=>"influence")
NeedsKeyword.create(:need_id=>n23.id, :keyword=>"pass")
NeedsKeyword.create(:need_id=>n23.id, :keyword=>"gas")
NeedsKeyword.create(:need_id=>n23.id, :keyword=>"burp")
NeedsKeyword.create(:need_id=>n23.id, :keyword=>"belch")
NeedsKeyword.create(:need_id=>n23.id, :keyword=>"slob")
NeedsKeyword.create(:need_id=>n23.id, :keyword=>"messy")
NeedsKeyword.create(:need_id=>n23.id, :keyword=>"embarrasses")
NeedsKeyword.create(:need_id=>n23.id, :keyword=>"embarrassment")

NeedsKeyword.create(:need_id=>n24.id, :keyword=>"peace")
NeedsKeyword.create(:need_id=>n24.id, :keyword=>"harmony")
NeedsKeyword.create(:need_id=>n24.id, :keyword=>"act")
NeedsKeyword.create(:need_id=>n24.id, :keyword=>"public")
NeedsKeyword.create(:need_id=>n24.id, :keyword=>"manners")
NeedsKeyword.create(:need_id=>n24.id, :keyword=>"social")
NeedsKeyword.create(:need_id=>n24.id, :keyword=>"moron")
NeedsKeyword.create(:need_id=>n24.id, :keyword=>"embarrassing")
NeedsKeyword.create(:need_id=>n24.id, :keyword=>"embarrassment")
NeedsKeyword.create(:need_id=>n24.id, :keyword=>"embarasing")
NeedsKeyword.create(:need_id=>n24.id, :keyword=>"embarasment")
NeedsKeyword.create(:need_id=>n24.id, :keyword=>"etiquette")

NeedsKeyword.create(:need_id=>n25.id,:keyword=>"sex")
NeedsKeyword.create(:need_id=>n25.id, :keyword=>"sexual")
NeedsKeyword.create(:need_id=>n25.id, :keyword=>"satisfaction")
NeedsKeyword.create(:need_id=>n25.id, :keyword=>"depravation")
NeedsKeyword.create(:need_id=>n25.id, :keyword=>"depravedness")
NeedsKeyword.create(:need_id=>n25.id, :keyword=>"cold")
NeedsKeyword.create(:need_id=>n25.id, :keyword=>"love")
NeedsKeyword.create(:need_id=>n25.id, :keyword=>"sexually")
NeedsKeyword.create(:need_id=>n25.id, :keyword=>"starved")
NeedsKeyword.create(:need_id=>n25.id, :keyword=>"intimacy")
NeedsKeyword.create(:need_id=>n25.id, :keyword=>"cold")
NeedsKeyword.create(:need_id=>n25.id, :keyword=>"distant")
NeedsKeyword.create(:need_id=>n25.id, :keyword=>"withdrawn")
NeedsKeyword.create(:need_id=>n25.id, :keyword=>"another")
NeedsKeyword.create(:need_id=>n25.id, :keyword=>"person")
NeedsKeyword.create(:need_id=>n25.id, :keyword=>"roommate")


#
# Test Users / Partners
#
# usr = User.create(:login=>'santiago', :email=>'santiago@mail.com', :password=>"santiago", :password_confirmation=>"santiago", :active=>true) 
# usr2 = User.create(:login=>'marcela', :email=>'marcela@mail.com', :password=>"marcela", :password_confirmation=>"marcela", :active=>true) 

# p1 = Partner.create(:user_id=>usr.id, :name=>'Santiago')
# p2 = Partner.create(:user_id=>usr2.id, :name=>'Marcela')

# p1.update_attributes(:my_partner_id=>p2.id)
# p2.update_attributes(:my_partner_id=>p1.id)

User.find_by_login('admin').destroy
admin = User.create(:login=>'admin', :email=>'adminEcc@gmail.com', :password=>"admin", :password_confirmation=>"admin", :active=>true)

# Roles
Role.find_by_name('admin').destroy
admin_role = Role.create(:name=>"admin")

#Add the admin user the admin role

admin.roles.push(admin_role)

#
# Test NSBGs
#
# NsbgNow.create(:need_id=>1, :partner_id=>2, :priority=>1, :hidden=>false, :score=>50)
# NsbgNow.create(:need_id=>2, :partner_id=>2, :priority=>2, :hidden=>false, :score=>90)
# NsbgNow.create(:need_id=>3, :partner_id=>2, :priority=>3, :hidden=>false, :score=>5)

#
# Test Action Agreements
#
ActionAgreementExample.delete_all
ActionAgreementExample.create(:need_id=>1, :plan_of_action=>"Plan of action example for need 1" )
ActionAgreementExample.create(:need_id=>2, :plan_of_action=>"Plan of action example for need 2" )
ActionAgreementExample.create(:need_id=>3, :plan_of_action=>"Plan of action example for need 3" )
ActionAgreementExample.create(:need_id=>4, :plan_of_action=>"Plan of action example for need 4" )
ActionAgreementExample.create(:need_id=>5, :plan_of_action=>"Plan of action example for need 5" )
ActionAgreementExample.create(:need_id=>6, :plan_of_action=>"Plan of action example for need 6" )


#
# CYN Questions
#
CynQuestion.delete_all
CynQuestion.create(:question=>"How much time would you like to spend on this every week?", :question_type=> 1, :priority=>1)
CynQuestion.create(:question=>"How good a communicator do you think you are?", :question_type=> 1,:priority=>2)
CynQuestion.create(:question=>"How about your partner?", :question_type=> 1,:priority=>3)
CynQuestion.create(:question=>"How motivated are you to make your relationship as successful as it can be?", :question_type=> 1,:priority=>4)      
CynQuestion.create(:question=>"How about your partner?", :question_type=> 1,:priority=>5)
CynQuestion.create(:question=>"What is the main reason you decided to try this out?",:question_type=> 2,:priority=>6)

#CynQuestion.create(:question=>"How much time would you like to spend on this every week?")
#CynQuestion.create(:question=>"How good a communicator do you think you are?")
#CynQuestion.create(:question=>"How about your partner?")
#CynQuestion.create(:question=>"How motivated are you to make your relationship as successful as it can be?")      
#CynQuestion.create(:question=>"How about your partner?")

CynAnswerOption.delete_all
CynAnswerOption.create(:cyn_question_id=>1, :answer_text=> "4 hours", :answer_option=>"1")
CynAnswerOption.create(:cyn_question_id=>1, :answer_text=> "3.5 hours", :answer_option=>"2")
CynAnswerOption.create(:cyn_question_id=>1, :answer_text=> "3 hours", :answer_option=>"3")
CynAnswerOption.create(:cyn_question_id=>1, :answer_text=> "2.5 hours", :answer_option=>"4")
CynAnswerOption.create(:cyn_question_id=>1, :answer_text=> "2 hours", :answer_option=>"5")
CynAnswerOption.create(:cyn_question_id=>1, :answer_text=> "1.5 hours", :answer_option=>"6")
CynAnswerOption.create(:cyn_question_id=>1, :answer_text=> "1 hour", :answer_option=>"7")
CynAnswerOption.create(:cyn_question_id=>1, :answer_text=> "half an hour", :answer_option=>"8")

CynAnswerOption.create(:cyn_question_id=>2, :answer_text=> "I'm a natural at communicating", :answer_option=>"a")
CynAnswerOption.create(:cyn_question_id=>2, :answer_text=> "I'm very good most of the time", :answer_option=>"b")    
CynAnswerOption.create(:cyn_question_id=>2, :answer_text=> "I’m about like most people, sometimes I get my message across", :answer_option=>"c")    
CynAnswerOption.create(:cyn_question_id=>2, :answer_text=> "I try but don’t always make myself clear", :answer_option=>"d")        
CynAnswerOption.create(:cyn_question_id=>2, :answer_text=> "I admit I need to work on this", :answer_option=>"e")            


CynAnswerOption.create(:cyn_question_id=>3, :answer_text=> "My partner is an effective, sensitive communicator", :answer_option=>"a")
CynAnswerOption.create(:cyn_question_id=>3, :answer_text=> "Most of the time my partner does a great job of communicating", :answer_option=>"b")    
CynAnswerOption.create(:cyn_question_id=>3, :answer_text=> "my partner communicates the way most people do", :answer_option=>"c")        
CynAnswerOption.create(:cyn_question_id=>3, :answer_text=> "my partner doesn’t always keep me in the loop", :answer_option=>"d")          
CynAnswerOption.create(:cyn_question_id=>3, :answer_text=> "I wish my partner would work on communicating better with me", :answer_option=>"e")

CynAnswerOption.create(:cyn_question_id=>4, :answer_text=> "I’m very motivated, I’ll do what it takes", :answer_option=>"a")
CynAnswerOption.create(:cyn_question_id=>4, :answer_text=> "I want to make things work between us", :answer_option=>"b")  
CynAnswerOption.create(:cyn_question_id=>4, :answer_text=> "I’m willing to give this a shot", :answer_option=>"c")      
CynAnswerOption.create(:cyn_question_id=>4, :answer_text=> "I’m motivated, but sometimes it’s hard", :answer_option=>"d")          
CynAnswerOption.create(:cyn_question_id=>4, :answer_text=> "I’m honestly not sure how much longer I can go on like this", :answer_option=>"e")          


CynAnswerOption.create(:cyn_question_id=>5, :answer_text=> "My partner is very motivated, and considers this a top priority", :answer_option=>"a")
CynAnswerOption.create(:cyn_question_id=>5, :answer_text=> "my partner wants to make things better", :answer_option=>"b")    
CynAnswerOption.create(:cyn_question_id=>5, :answer_text=> "middle of the road, but willing to try", :answer_option=>"c")        
CynAnswerOption.create(:cyn_question_id=>5, :answer_text=> "my partner doesn’t always want to think about us", :answer_option=>"d")        
CynAnswerOption.create(:cyn_question_id=>5, :answer_text=> "I wish my partner wanted to try harder", :answer_option=>"e")

CynAnswerOption.create(:cyn_question_id=>6, :answer_text=> "maintain and grow already great relationship", :answer_option=>"1")
CynAnswerOption.create(:cyn_question_id=>6, :answer_text=> "resolve recurrent issues", :answer_option=>"2", :user_text=>false)    


#
# WUC Options
#
Option.delete_all
Option.create(:label=>"good or below", :value=>"80", :domain=>"WUC.TriggerLevel")
Option.create(:label=>"Ok or below", :value=>"60", :domain=>"WUC.TriggerLevel")    
Option.create(:label=>"sad or below", :value=>"40", :domain=>"WUC.TriggerLevel")    
Option.create(:label=>"desperate", :value=>"20", :domain=>"WUC.TriggerLevel")    
Option.create(:label=>"choose your ", :value=>"-1", :domain=>"WUC.TriggerLevel")        

#Option for lenght in hours
Option.create(:label=>"1/2 a Day", :value=>"12", :domain=>"WUC.LengthOfDissatisfaction")
Option.create(:label=>"1 Day", :value=>"24", :domain=>"WUC.LengthOfDissatisfaction")    
Option.create(:label=>"2 Days", :value=>"48", :domain=>"WUC.LengthOfDissatisfaction")
Option.create(:label=>"3 Days", :value=>"72", :domain=>"WUC.LengthOfDissatisfaction")
Option.create(:label=>"4 Days", :value=>"96", :domain=>"WUC.LengthOfDissatisfaction")    
Option.create(:label=>"5 Days", :value=>"110", :domain=>"WUC.LengthOfDissatisfaction")    
Option.create(:label=>"1 Week", :value=>"168", :domain=>"WUC.LengthOfDissatisfaction")
Option.create(:label=>"10 Days", :value=>"240", :domain=>"WUC.LengthOfDissatisfaction")
Option.create(:label=>"2 Weeks", :value=>"336", :domain=>"WUC.LengthOfDissatisfaction")    
Option.create(:label=>"3 Weeks", :value=>"504", :domain=>"WUC.LengthOfDissatisfaction")

Option.create(:label=>"Yellow", :value=>"Yellow", :domain=>"WUC.AlertLevel")
Option.create(:label=>"Orange", :value=>"Orange", :domain=>"WUC.AlertLevel")
Option.create(:label=>"Red", :value=>"Red", :domain=>"WUC.AlertLevel")
Option.create(:label=>"Purple", :value=>"Purple", :domain=>"WUC.AlertLevel")            

Option.create(:label=>"1 position increase", :value=>"1", :domain=>"WUC.UrgencyChange")    
Option.create(:label=>"2 position increase", :value=>"2", :domain=>"WUC.UrgencyChange")        
Option.create(:label=>"3 position increase", :value=>"3", :domain=>"WUC.UrgencyChange")        
Option.create(:label=>"4 position increase", :value=>"4", :domain=>"WUC.UrgencyChange")    
Option.create(:label=>"5 position or more increase", :value=>"5", :domain=>"WUC.UrgencyChange")
Option.create(:label=>"new prioritized need", :value=>"100", :domain=>"WUC.UrgencyChange")    
Option.create(:label=>"prioritized need removed", :value=>"-100", :domain=>"WUC.UrgencyChange")    
Option.create(:label=>"1 position decrease", :value=>"-1", :domain=>"WUC.UrgencyChange")    
Option.create(:label=>"2 position decrease", :value=>"-2", :domain=>"WUC.UrgencyChange")    
Option.create(:label=>"3 position decrease", :value=>"-3", :domain=>"WUC.UrgencyChange")    
Option.create(:label=>"4 position decrease", :value=>"-4", :domain=>"WUC.UrgencyChange")    
Option.create(:label=>"5 position or more decrease", :value=>"-5", :domain=>"WUC.UrgencyChange")

Option.create(:label=>"Text me", :value=>"0", :domain=>"SendVia")
Option.create(:label=>"Email me", :value=>"1", :domain=>"SendVia")    
Option.create(:label=>"Send me both", :value=>"2", :domain=>"SendVia")    

#
# Options for Action Agreement
#
Option.create(:label=>"after", :value=>"after", :domain=>"ActionAgreement.PlannedTime.When")
Option.create(:label=>"before", :value=>"before", :domain=>"ActionAgreement.PlannedTime.When")    
Option.create(:label=>"during", :value=>"during", :domain=>"ActionAgreement.PlannedTime.When")    
Option.create(:label=>"at", :value=>"at", :domain=>"ActionAgreement.PlannedTime.When")

    Option.create(:label=>"dinner", :value=>"dinner", :domain=>"ActionAgreement.PlannedTime.Activities")
    Option.create(:label=>"going to sleep", :value=>"going to sleep", :domain=>"ActionAgreement.PlannedTime.Activities")
    Option.create(:label=>"school days", :value=>"school days", :domain=>"ActionAgreement.PlannedTime.Activities")
    Option.create(:label=>"weekends", :value=>"weekends", :domain=>"ActionAgreement.PlannedTime.Activities")
    
    Option.create(:label=>"Monday", :value=>"1", :domain=>"Weekdays")
    Option.create(:label=>"Tuesday", :value=>"2", :domain=>"Weekdays")
    Option.create(:label=>"Wednesday", :value=>"3", :domain=>"Weekdays")
    Option.create(:label=>"Thursday", :value=>"4", :domain=>"Weekdays")
    Option.create(:label=>"Friday", :value=>"5", :domain=>"Weekdays")
    Option.create(:label=>"Saturday", :value=>"6", :domain=>"Weekdays")
    Option.create(:label=>"Sunday", :value=>"7", :domain=>"Weekdays")
    
    Option.create(:label=>"1", :value=>"1", :domain=>"Hours")
    Option.create(:label=>"2", :value=>"2", :domain=>"Hours")
    Option.create(:label=>"3", :value=>"3", :domain=>"Hours")
    Option.create(:label=>"4", :value=>"4", :domain=>"Hours")
    Option.create(:label=>"5", :value=>"5", :domain=>"Hours")
    Option.create(:label=>"6", :value=>"6", :domain=>"Hours")
    Option.create(:label=>"7", :value=>"7", :domain=>"Hours")
    Option.create(:label=>"8", :value=>"8", :domain=>"Hours")
    Option.create(:label=>"9", :value=>"9", :domain=>"Hours")
    Option.create(:label=>"10", :value=>"10", :domain=>"Hours")
    Option.create(:label=>"11", :value=>"11", :domain=>"Hours")
    Option.create(:label=>"12", :value=>"12", :domain=>"Hours")
    
    Option.create(:label=>"am", :value=>"0", :domain=>"Hours.ampm")
    Option.create(:label=>"pm", :value=>"1", :domain=>"Hours.ampm")

    #
    # Options for Time
    #
    Option.delete_all(:domain=>"Hours")    
    Option.delete_all(:domain=>"Hours.ampm")    
        
    Option.create(:label=>"1", :value=>"1", :domain=>"Time.Hours")
    Option.create(:label=>"2", :value=>"2", :domain=>"Time.Hours")
    Option.create(:label=>"3", :value=>"3", :domain=>"Time.Hours")
    Option.create(:label=>"4", :value=>"4", :domain=>"Time.Hours")
    Option.create(:label=>"5", :value=>"5", :domain=>"Time.Hours")
    Option.create(:label=>"6", :value=>"6", :domain=>"Time.Hours")
    Option.create(:label=>"7", :value=>"7", :domain=>"Time.Hours")
    Option.create(:label=>"8", :value=>"8", :domain=>"Time.Hours")
    Option.create(:label=>"9", :value=>"9", :domain=>"Time.Hours")
    Option.create(:label=>"10", :value=>"10", :domain=>"Time.Hours")
    Option.create(:label=>"11", :value=>"11", :domain=>"Time.Hours")
    Option.create(:label=>"12", :value=>"12", :domain=>"Time.Hours")
    
    Option.create(:label=>"00", :value=>"00", :domain=>"Time.Minutes")
    Option.create(:label=>"15", :value=>"15", :domain=>"Time.Minutes")
    Option.create(:label=>"30", :value=>"30", :domain=>"Time.Minutes")
    Option.create(:label=>"45", :value=>"45", :domain=>"Time.Minutes")
    
    Option.create(:label=>"am", :value=>"0", :domain=>"Time.ampm")
    Option.create(:label=>"pm", :value=>"1", :domain=>"Time.ampm")

    #
    # Action Agreement Evaluation Questions
    #
    ActionAgreementEvaluationQuestion.delete_all
    ActionAgreementEvaluationQuestion.create(:question=>"What was the effect the Action Agreement had on the interactions between you and your partner?", :domain=>"ActionAgreementEvaluationQuestion.Effect")
    ActionAgreementEvaluationQuestion.create(:question=>"Do you think the Action Agreement helped you and your partner accomplish the desired objective?", :domain=>"ActionAgreementEvaluationQuestion.Objective")
    ActionAgreementEvaluationQuestion.create(:question=>"Did you follow the Action Agreement according to the plan?", :domain=>"ActionAgreementEvaluationQuestion.Follow")
    ActionAgreementEvaluationQuestion.create(:question=>"Do you have any thoughts about the Action Agreement?  Any ideas about how to make it work better next time?", :domain=>"OpenAnswer")
   
    Option.create(:label=> "Very Positive", :value=> "Very Positive", :domain=>"ActionAgreementEvaluationQuestion.Effect")
    Option.create(:label=> "Positive", :value=> "Positive", :domain=>"ActionAgreementEvaluationQuestion.Effect")   
    Option.create(:label=> "Neutral", :value=> "Neutral", :domain=>"ActionAgreementEvaluationQuestion.Effect")   
    Option.create(:label=> "Negative", :value=> "Negative", :domain=>"ActionAgreementEvaluationQuestion.Effect")   
    
    Option.create(:label=> "Completely", :value=> "Completely", :domain=>"ActionAgreementEvaluationQuestion.Objective")
    Option.create(:label=> "Yes", :value=> "Yes", :domain=>"ActionAgreementEvaluationQuestion.Objective")    
    Option.create(:label=> "Sort of", :value=> "Sort of", :domain=>"ActionAgreementEvaluationQuestion.Objective")
    Option.create(:label=> "A little bit", :value=> "A little bit", :domain=>"ActionAgreementEvaluationQuestion.Objective")
    Option.create(:label=> "Not at all", :value=> "Not at all", :domain=>"ActionAgreementEvaluationQuestion.Objective")
    
    Option.create(:label=> "I followed through completely", :value=> "I followed through completely", :domain=>"ActionAgreementEvaluationQuestion.Follow")    
    Option.create(:label=> "Most of the time I did", :value=> "Most of the time I did", :domain=>"ActionAgreementEvaluationQuestion.Follow")
    Option.create(:label=> "About half and half, which was a big step", :value=> "About half and half, which was a big step", :domain=>"ActionAgreementEvaluationQuestion.Follow")
    Option.create(:label=> "I wish I’d done a little better", :value=> "I wish I’d done a little better", :domain=>"ActionAgreementEvaluationQuestion.Follow")
    Option.create(:label=> "Unfortunately it slipped through the cracks", :value=> "Unfortunately it slipped through the cracks", :domain=>"ActionAgreementEvaluationQuestion.Follow")
    Option.create(:label=> "Not applicable", :value=> "Not applicable", :domain=>"ActionAgreementEvaluationQuestion.Follow")    
    
    CoupleQuizzesOption.delete_all
    CoupleQuizzesQuestion.delete_all
    cqq1 = CoupleQuizzesQuestion.create(:question=>"Are you able to stick up for yourself with your partner?")
    CoupleQuizzesOption.create(:label=>"Usually", :value=>"1", :points=>1, :couple_quizzes_question_id=>cqq1.id)
    CoupleQuizzesOption.create(:label=>"Often", :value=>"2", :points=>2, :couple_quizzes_question_id=>cqq1.id)    
    CoupleQuizzesOption.create(:label=>"Rarely", :value=>"3", :points=>3, :couple_quizzes_question_id=>cqq1.id)    
    CoupleQuizzesOption.create(:label=>"Never", :value=>"4", :points=>4, :couple_quizzes_question_id=>cqq1.id)    

    cqq2 = CoupleQuizzesQuestion.create(:question=>"What do your parents hate most about you and your sweetie?")
    CoupleQuizzesOption.create(:label=>"They can't figure out if we're really a couple or just lab partners", :value=>"1", :points=>1, :couple_quizzes_question_id=>cqq2.id)
    CoupleQuizzesOption.create(:label=>"They think we slobber all over each other every chance we get", :value=>"2", :points=>2, :couple_quizzes_question_id=>cqq2.id)    
    CoupleQuizzesOption.create(:label=>"They think we're always up to no good. And they're right", :value=>"3", :points=>3, :couple_quizzes_question_id=>cqq2.id)    
    CoupleQuizzesOption.create(:label=>"They hate that we're always breaking up and getting back together", :value=>"4", :points=>4, :couple_quizzes_question_id=>cqq2.id)    
    CoupleQuizzesOption.create(:label=>"They hate that we're always breaking up and getting back together", :value=>"5", :points=>4, :couple_quizzes_question_id=>cqq2.id)        
    CoupleQuizzesOption.create(:label=>"They hate everything---that's why we keep this relationship on the down-low", :value=>"6", :points=>4, :couple_quizzes_question_id=>cqq2.id)            
    CoupleQuizzesOption.create(:label=>"Nothing--they think we're made for each other!", :value=>"7", :points=>0, :couple_quizzes_question_id=>cqq2.id)   
    
    CoupleQuizzesScore.create(:minimum=>0, :maximum=>12, :description=>"You and your partner need to learn more about what makes each other tick to present a united front")
    CoupleQuizzesScore.create(:minimum=>13, :maximum=>18, :description=>"You and your partner can work well together sometimes, but you’re not always on the same team")    
    CoupleQuizzesScore.create(:minimum=>19, :maximum=>24, :description=>"Yes, you’re a team that plays well enough together to pull off some capers!")        
    CoupleQuizzesScore.create(:minimum=>25, :maximum=>30, :description=>"If it had been you and your partner starring in the movie Mr. and Mrs. Smith, everything would have gone off like clockwork and there would have been a lot less fighting!")


  GameLocation.delete_all
  gloc1 = GameLocation.create(:location=>"going to bed at night")
  gloc2 = GameLocation.create(:location=>"riding in the car")
  gloc3 = GameLocation.create(:location=>"while biking")
  gloc4 = GameLocation.create(:location=>"while walking")
  GameLocation.create(:location=>"leaving the house in the morning")
  GameLocation.create(:location=>"coming home at night")
  GameLocation.create(:location=>"during meals")
  GameLocation.create(:location=>"at restaurants")
  GameLocation.create(:location=>"while shopping")
  GameLocation.create(:location=>"while watching tv")
  GameLocation.create(:location=>"while you wait")  
  GameLocation.create(:location=>"at the office")  
  GameLocation.create(:location=>"while you play sports")  
  GameLocation.create(:location=>"doing chores")  
  GameLocation.create(:location=>"making decisions")  
  GameLocation.create(:location=>"when you’re alone")  
  
  GameCategory.delete_all
  gcat1 = GameCategory.create(:category=>"Physical")
  gcat2 = GameCategory.create(:category=>"Artistic")  
  gcat3 = GameCategory.create(:category=>"Mental")  
  gcat4 = GameCategory.create(:category=>"Dramatic")  

  Game.delete_all
  Game.create(:name=>"Super Game #1",:game_location_id=>1, :rules=>"This are the rules 1", :tips=>"Tips for 1", :contradictions=>"Contradiction for 1", :game_category_id=>gcat1.id)    
    Game.create(:name=>"Game 2",:game_location_id=>gloc2.id, :rules=>"This are the rules 2", :tips=>"Tips for 2", :contradictions=>"Contradiction for 2", :game_category_id=>gcat2.id)    
    Game.create(:name=>"Game 11",:game_location_id=>gloc1.id, :rules=>"This are the rules 11", :tips=>"Tips for 11", :contradictions=>"Contradiction for 11", :game_category_id=>gcat1.id)      
    Game.create(:name=>"Game 3",:game_location_id=>gloc3.id, :rules=>"This are the rules 3", :tips=>"Tips for 3", :contradictions=>"Contradiction for 3", :game_category_id=>gcat3.id)        
    Game.create(:name=>"Game 4",:game_location_id=>gloc4.id, :rules=>"This are the rules 4", :tips=>"Tips for 4", :contradictions=>"Contradiction for 4", :game_category_id=>gcat4.id)      

ContentCopy.delete_all    
ContentCopy.create(:domain=>"Cyn.Questionnaire", :copy=>"First let’s get a general idea of how you and your partner relate to each other, and what you’d like to make better.")
ContentCopy.create(:domain=>"Cyn.ChooseYourNeeds", :copy=>"Our goal is to help you and your partner meet each other’s needs.  The first step is finding out where your needs are not being completely satisfied. We’ve listed 8 needs on the left which experts find to be predictive of happy, solid relationships.  Take a look at the descriptions that display when  you click on these needs, and consider whether any of them are applicable to you and your partner.  both partners meet each others needs in these areas, it’s a strong predictor of a happy relationship.  There may be other needs that are important to you, and we’ve listed some that come up frequently.  If you don’t see a need  that relates to what’s most important to you, use the fill-in field at the end.  Before you do so, take a look at the  descriptions of the listed needs, it may be that one of these is actually the root of your situation.")
ContentCopy.create(:domain=>"Cyn.RateYourNeeds", :copy=>"Now think about why you selected the needs that you did. Use the sliders to set your current satisfaction levels for the needs that are important to you.  You can click the need to display some further information about how it can impact relationships, and you can go back to the previous step if you want to add or change some of your needs. Here are the satisfaction levels you set.  Now we’d like to know which of them concern you most - the areas you want to address right away.  Sometimes this isn’t the same as where you ranked your satisfaction as lowest.  Inviting your partner to assess their own needs and starting a 2-way dialogue is the next step.  
We understand that you and your partner may want to start out slowly when you begin considering the way you feel about some topics.  You can be the judge of what you want to show your partner at this time.  Use the MOVE buttons to put needs you want to focus on first to the left, and lower priorities to the right.  You can change the lineup of needs that will be shown to your partner by moving touchy topics over to the reserve area on the right.  These needs will stay there for you to think about - you can move them to the area on the left when you’re ready to share them with your partner.")
ContentCopy.create(:domain=>"Cyn.Review", :copy=>"Review your choices")
ContentCopy.create(:domain=>"Cyn.LinkToMyPartner", :copy=>"Would you like to logout so your partner can log in right here and complete their next steps?")
